// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function EmitError(arg1) {
  return window['go']['main']['App']['EmitError'](arg1);
}

export function NewTab(arg1) {
  return window['go']['main']['App']['NewTab'](arg1);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SetActiveDatabase(arg1, arg2) {
  return window['go']['main']['App']['SetActiveDatabase'](arg1, arg2);
}

export function TestConnect(arg1) {
  return window['go']['main']['App']['TestConnect'](arg1);
}
