// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CancelQuery(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<model.ConnectResult>;

export function EmitError(arg1:string):Promise<void>;

export function NewTab(arg1:string):Promise<model.ConnectResult>;

export function RunQuery(arg1:string,arg2:string):Promise<Array<model.SQLResult>>;

export function SetActiveDatabase(arg1:string,arg2:string):Promise<string>;

export function TestConnect(arg1:string):Promise<void>;
